### ISSUE TITLE
Cannot get this to run

### ISSUE THREAD

**Issue by inijman** [TheJacksonLaboratory/HPOworkbench#22]
HI, Iḿ very interested in HPOWorkbench, but cannot get it to run: The windows exe just wont start and does not seem to do anything (java 1.8.0144). The jar file under Ubuntu 16.04 reports "Error: Could not find or load main class org.monarchinitiative.hpoworkbench.Main".

During building from src with Maven i Get:

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce) on project HPOworkbench: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.

I would appreciate some help with setting it up.

**Comment by pnrobinson** [comment]
Hi 
can you let me know which version you are using? If you are not using the latest version (v0.1.11),
please update this and try again.
I just tried the latest jar file with my Ubuntu and everything seemed to work ok.
https://github.com/TheJacksonLaboratory/HPOworkbench/releases/tag/v0.1.11
I think that you may be using the v0.1.10 version, which did have an issue, unfortunately.

**Comment by pnrobinson** [comment]
I am going to assume this is running now with the latest version  https://github.com/TheJacksonLaboratory/HPOworkbench/releases/tag/v0.1.11
Please reopen this issue if there are any other problems.
