### ISSUE TITLE
hierarchical summary

### ISSUE THREAD

**Issue by cmungall** [TheJacksonLaboratory/HPOworkbench#3]
it seems to be stuck on my first choice `Abnormal mitochondria in muscle tissue`, and when I export it I only get one row / one level

Export ontology works (Parent field still blank)

**Comment by pnrobinson** [comment]
Abnormal mitochondria in muscle tissue does not have children!
The code for choosing parents does not work in the "Export ontology as Excel file" (it does for the hierarchical summary). I am trying to figure out  a more elegant way of coding this.

**Comment by pnrobinson** [comment]
This is implemented now
