### ISSUE TITLE
Window

### ISSUE THREAD

**Issue by starumugam** [TheJacksonLaboratory/HPOworkbench#38]
Where can I find windows version of HPOworkbench?
Thanks

**Comment by pnrobinson** [comment]
Hi!
You can download the latest Release
https://github.com/TheJacksonLaboratory/HPOworkbench/releases/tag/v.1.1.0
This is a "jar" file, which will run if your windows system has Java installed (version 1.8). 
Probably it will work if you download the file HpoWorkbench.jar to your Desktop (or whereever) and then just double click on it. Alternatively, you can open a terminal and enter
```
java -jar HpoWorkbench.jar 
```
Could you please try this and let me know if it works?

**Comment by pnrobinson** [comment]
There is now a newer release. It should work under windows. I am closing this issue for now, please reopen if there are problems!

**Comment by starumugam** [comment]
Thanks Dr. Robinson
Jar file not working on windows. I will try the new version.

Thanks
Suva
