### ISSUE TITLE
Download HPO annotations

### ISSUE THREAD

**Issue by hekselman** [TheJacksonLaboratory/HPOworkbench#50]
Hi! Hope to use this tool :) I tried to start, but can't seem to be able to download the HPO annotations file. I think the problem is in the Charite's site which is down right now...
Any solutions?
Thanks, Idan.

**Comment by pnrobinson** [comment]
Thanks for pointing this out. An update for this tool was overdue anyway. The issue was that an upsteam URL had changed. I cleaned up a few other things and made a new release

https://github.com/TheJacksonLaboratory/HPOworkbench/releases/tag/v1.6.0

It should work now.

**Comment by hekselman** [comment]
It is! :) thank you so much!
