### ISSUE TITLE
Import local hp obo file not working

### ISSUE THREAD

**Issue by cmungall** [TheJacksonLaboratory/HPOworkbench#7]
![image](https://user-images.githubusercontent.com/50745/34955634-32416082-f9da-11e7-9144-4ec956ccc0ee.png)

I get:

![image](https://user-images.githubusercontent.com/50745/34955638-39d2e1f4-f9da-11e7-860a-4853a794a772.png)

First, it's not clear why it's complaining about the annot file when I'm refreshing the ont file

Second, the file is actually there:

```
$ ls -alt ~/.hpoworkbench/phenotype_annotation.tab 
-rw-r--r--  1 cjm  staff  18896952 Jan  3 08:57 /Users/cjm/.hpoworkbench/phenotype_annotation.tab

```

**Comment by cmungall** [comment]
This still happens after I refresh the annot file

**Comment by cmungall** [comment]
console log not much help:

```
 INFO - 2018-01-15 10:14:41 - Parsing OBO file /Users/cjm/tmp/hp.obo...
```

**Comment by pnrobinson** [comment]
That is working for me. One thing is that current you need to restart the program after importing hp.obo and phenotype_annotation.tab the first time. I will fix this.

**Comment by cmungall** [comment]
I had the same error after quitting and restarting...

**Comment by pnrobinson** [comment]
This is working now, please retry.
